export const padelCourts = [
  {
    id: "06e76988-7a5a-4648-8dcd-c2c91281c408",
    isHidden: false,
    name: "Bana 1",
    bookableType: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
    bookableEntityType: {
      id: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
      name: "Padel Dubbel",
      active: true,
      translationName: "",
      sportType: {
        name: "Padel",
        active: true,
        translationName: "Padel",
        sportTypeProperties: [
          {
            id: "3ba46aff-4976-4394-a0fb-0951e3e9857d",
            name: "Double",
            active: true,
            translationName: "Padel-double-court",
            defaultPlayers: 4,
            defaultSlotLength: 30,
            defaultMinNumberOfSlots: 2,
            defaultMaxNumberOfSlots: null,
          },
        ],
        id: "c9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
      defaultNumberOfPlayers: 4,
      defaultSlotLength: 30,
      defaultMinNumberOfSlots: 2,
      defaultMaxNumberOfSlots: 0,
      dynamicPricing: false,
      freezedPricing: false,
    },
    openHours: [],
    vendorReferences: [
      {
        vendorReferenceId: "1",
        timeOffsetDoor: {
          start: -1800,
          end: 1800,
        },
        timeOffsetLights: {
          start: -600,
          end: 600,
        },
        id: "D9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
    ],
    isDeleted: false,
    createdAt: null,
    detetedAt: null,
    deletedBy: null,
    parentEntityId: null,
    isMultiCourt: false,
    isHiddenChangeLog: [],
  },
  {
    id: "40db94dd-90b2-492d-b7aa-9c473d058d6b",
    isHidden: false,
    name: "Bana 2",
    bookableType: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
    bookableEntityType: {
      id: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
      name: "Padel Dubbel",
      active: true,
      translationName: "",
      sportType: {
        name: "Padel",
        active: true,
        translationName: "Padel",
        sportTypeProperties: [
          {
            id: "3ba46aff-4976-4394-a0fb-0951e3e9857d",
            name: "Double",
            active: true,
            translationName: "Padel-double-court",
            defaultPlayers: 4,
            defaultSlotLength: 30,
            defaultMinNumberOfSlots: 2,
            defaultMaxNumberOfSlots: null,
          },
        ],
        id: "c9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
      defaultNumberOfPlayers: 4,
      defaultSlotLength: 30,
      defaultMinNumberOfSlots: 2,
      defaultMaxNumberOfSlots: 0,
      dynamicPricing: false,
      freezedPricing: false,
    },
    openHours: [],
    vendorReferences: [
      {
        vendorReferenceId: "2",
        timeOffsetDoor: {
          start: -1800,
          end: 1800,
        },
        timeOffsetLights: {
          start: -600,
          end: 600,
        },
        id: "D9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
    ],
    isDeleted: false,
    createdAt: null,
    detetedAt: null,
    deletedBy: null,
    parentEntityId: null,
    isMultiCourt: false,
    isHiddenChangeLog: [],
  },
  {
    id: "b6f7620b-5dab-4f86-b04f-4aa87a25f172",
    isHidden: false,
    name: "Bana 3 (Center court) ",
    bookableType: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
    bookableEntityType: {
      id: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
      name: "Padel Dubbel",
      active: true,
      translationName: "",
      sportType: {
        name: "Padel",
        active: true,
        translationName: "Padel",
        sportTypeProperties: [
          {
            id: "3ba46aff-4976-4394-a0fb-0951e3e9857d",
            name: "Double",
            active: true,
            translationName: "Padel-double-court",
            defaultPlayers: 4,
            defaultSlotLength: 30,
            defaultMinNumberOfSlots: 2,
            defaultMaxNumberOfSlots: null,
          },
        ],
        id: "c9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
      defaultNumberOfPlayers: 4,
      defaultSlotLength: 30,
      defaultMinNumberOfSlots: 2,
      defaultMaxNumberOfSlots: 0,
      dynamicPricing: false,
      freezedPricing: false,
    },
    openHours: [],
    vendorReferences: [
      {
        vendorReferenceId: "3",
        timeOffsetDoor: {
          start: -1800,
          end: 1800,
        },
        timeOffsetLights: {
          start: -600,
          end: 600,
        },
        id: "D9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
    ],
    isDeleted: false,
    createdAt: null,
    detetedAt: null,
    deletedBy: null,
    parentEntityId: null,
    isMultiCourt: false,
    isHiddenChangeLog: [],
  },
  {
    id: "d08fb858-2198-4ccd-aecf-81f89e115662",
    isHidden: false,
    name: "Bana 4",
    bookableType: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
    bookableEntityType: {
      id: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
      name: "Padel Dubbel",
      active: true,
      translationName: "",
      sportType: {
        name: "Padel",
        active: true,
        translationName: "Padel",
        sportTypeProperties: [
          {
            id: "3ba46aff-4976-4394-a0fb-0951e3e9857d",
            name: "Double",
            active: true,
            translationName: "Padel-double-court",
            defaultPlayers: 4,
            defaultSlotLength: 30,
            defaultMinNumberOfSlots: 2,
            defaultMaxNumberOfSlots: null,
          },
        ],
        id: "c9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
      defaultNumberOfPlayers: 4,
      defaultSlotLength: 30,
      defaultMinNumberOfSlots: 2,
      defaultMaxNumberOfSlots: 0,
      dynamicPricing: false,
      freezedPricing: false,
    },
    openHours: [],
    vendorReferences: [
      {
        vendorReferenceId: "4",
        timeOffsetDoor: {
          start: -1800,
          end: 1800,
        },
        timeOffsetLights: {
          start: -600,
          end: 600,
        },
        id: "D9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
    ],
    isDeleted: false,
    createdAt: null,
    detetedAt: null,
    deletedBy: null,
    parentEntityId: null,
    isMultiCourt: false,
    isHiddenChangeLog: [],
  },
  {
    id: "80f10194-73cd-4e4d-b4f3-bf2e3933a2d5",
    isHidden: false,
    name: "Bana 5",
    bookableType: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
    bookableEntityType: {
      id: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
      name: "Padel Dubbel",
      active: true,
      translationName: "",
      sportType: {
        name: "Padel",
        active: true,
        translationName: "Padel",
        sportTypeProperties: [
          {
            id: "3ba46aff-4976-4394-a0fb-0951e3e9857d",
            name: "Double",
            active: true,
            translationName: "Padel-double-court",
            defaultPlayers: 4,
            defaultSlotLength: 30,
            defaultMinNumberOfSlots: 2,
            defaultMaxNumberOfSlots: null,
          },
        ],
        id: "c9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
      defaultNumberOfPlayers: 4,
      defaultSlotLength: 30,
      defaultMinNumberOfSlots: 2,
      defaultMaxNumberOfSlots: 0,
      dynamicPricing: false,
      freezedPricing: false,
    },
    openHours: [],
    vendorReferences: [
      {
        vendorReferenceId: "5",
        timeOffsetDoor: {
          start: -1800,
          end: 1800,
        },
        timeOffsetLights: {
          start: -600,
          end: 600,
        },
        id: "D9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
    ],
    isDeleted: false,
    createdAt: null,
    detetedAt: null,
    deletedBy: null,
    parentEntityId: null,
    isMultiCourt: false,
    isHiddenChangeLog: [],
  },
  {
    id: "4c68a677-639e-4aa1-aad7-c514d00730d6",
    isHidden: false,
    name: "Bana 6",
    bookableType: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
    bookableEntityType: {
      id: "118b69ad-e79f-4fa1-93d9-468ee5f0abfc",
      name: "Padel Dubbel",
      active: true,
      translationName: "",
      sportType: {
        name: "Padel",
        active: true,
        translationName: "Padel",
        sportTypeProperties: [
          {
            id: "3ba46aff-4976-4394-a0fb-0951e3e9857d",
            name: "Double",
            active: true,
            translationName: "Padel-double-court",
            defaultPlayers: 4,
            defaultSlotLength: 30,
            defaultMinNumberOfSlots: 2,
            defaultMaxNumberOfSlots: null,
          },
        ],
        id: "c9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
      defaultNumberOfPlayers: 4,
      defaultSlotLength: 30,
      defaultMinNumberOfSlots: 2,
      defaultMaxNumberOfSlots: 0,
      dynamicPricing: false,
      freezedPricing: false,
    },
    openHours: [],
    vendorReferences: [
      {
        vendorReferenceId: "6",
        timeOffsetDoor: {
          start: -1800,
          end: 1800,
        },
        timeOffsetLights: {
          start: -600,
          end: 600,
        },
        id: "D9077ebb-72b2-49a3-a828-baf3b8d62ed9",
      },
    ],
    isDeleted: false,
    createdAt: null,
    detetedAt: null,
    deletedBy: null,
    parentEntityId: null,
    isMultiCourt: false,
    isHiddenChangeLog: [],
  },
];
